# Turn several text files into one C++ header holding each as a string
# constant beside its file name. The sibling of EmbedText.cmake for a set
# of sources that travel together.
# Called as a script:
#   cmake -DINPUTS=a.c;b.c -DOUTPUT=... -DNAME=... -P EmbedTexts.cmake
#
# The header declares
#
#   struct NAME_Entry { const char* name; const char* text; };
#   static const NAME_Entry NAME[] = { ... };
#   static const unsigned long NAME_COUNT = ...;
#
# Each text is spelled out as bytes, as EmbedText.cmake does. A string
# literal over 65536 characters is beyond what the standard guarantees,
# Clang refuses one under -Wpedantic, and the assembly guide is longer.

set(arrays "")
set(body "")
set(count 0)
foreach(input IN LISTS INPUTS)
  file(READ "${input}" hex HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "'\\\\x\\1'," bytes "${hex}")
  string(REGEX REPLACE "(('\\\\x[0-9a-f][0-9a-f]',){12})" "\\1\n  " bytes "${bytes}")
  get_filename_component(base "${input}" NAME)
  string(APPEND arrays "static const char ${NAME}_${count}[] = {\n  ${bytes} 0\n};\n")
  string(APPEND body "  {\"${base}\", ${NAME}_${count}},\n")
  math(EXPR count "${count} + 1")
endforeach()

file(WRITE "${OUTPUT}"
  "// Generated by cmake/EmbedTexts.cmake. Do not edit.\n"
  "#pragma once\n"
  "struct ${NAME}_Entry { const char* name; const char* text; };\n"
  "${arrays}"
  "static const ${NAME}_Entry ${NAME}[] = {\n${body}};\n"
  "static const unsigned long ${NAME}_COUNT = ${count};\n")
