# Turn several text files into one C++ header holding each as a string
# constant beside its file name. The sibling of EmbedText.cmake for a set
# of sources that travel together.
# Called as a script:
#   cmake -DINPUTS=a.c;b.c -DOUTPUT=... -DNAME=... -P EmbedTexts.cmake
#
# The header declares
#
#   struct NAME_Entry { const char* name; const char* text; };
#   static const NAME_Entry NAME[] = { ... };
#   static const unsigned long NAME_COUNT = ...;

set(delim "sc8embed")
set(body "")
set(count 0)
foreach(input IN LISTS INPUTS)
  file(READ "${input}" content)
  get_filename_component(base "${input}" NAME)
  string(APPEND body "  {\"${base}\", R\"${delim}(${content})${delim}\"},\n")
  math(EXPR count "${count} + 1")
endforeach()

file(WRITE "${OUTPUT}"
  "// Generated by cmake/EmbedTexts.cmake. Do not edit.\n"
  "#pragma once\n"
  "struct ${NAME}_Entry { const char* name; const char* text; };\n"
  "static const ${NAME}_Entry ${NAME}[] = {\n${body}};\n"
  "static const unsigned long ${NAME}_COUNT = ${count};\n")
